name: phronesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.19
  - numpy=1.26.4
  - scipy=1.13.1
  - networkx=3.3
  - matplotlib=3.9.2
  - pandas=2.2.2
  - pyyaml=6.0.1
  - tqdm=4.66.5
  - seaborn=0.13.2
  - pytest=8.3.2
  - pytest-cov=5.0.0
  - pip
